# Generated by Django 2.1.7 on 2019-03-23 13:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20190323_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='writers',
        ),
        migrations.AddField(
            model_name='book',
            name='writers',
            field=models.ManyToManyField(blank=True, to='api.Writer'),
        ),
        migrations.AlterField(
            model_name='borrowitem',
            name='borrow_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 23, 14, 43, 42, 152078)),
        ),
        migrations.AlterField(
            model_name='borrowitem',
            name='return_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 23, 14, 43, 42, 152078)),
        ),
    ]
