# Generated by Django 2.1.7 on 2019-03-23 14:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20190323_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowitem',
            name='borrow_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 23, 15, 46, 42, 900145)),
        ),
        migrations.AlterField(
            model_name='borrowitem',
            name='return_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 23, 15, 46, 42, 900145)),
        ),
        migrations.RemoveField(
            model_name='electronic',
            name='manufacturer',
        ),
        migrations.AddField(
            model_name='electronic',
            name='manufacturer',
            field=models.ManyToManyField(blank=True, to='api.Manufacturer'),
        ),
    ]
