# Generated by Django 2.1.7 on 2019-03-23 15:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20190323_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='borrow_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='borrowitem',
            name='borrow_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 23, 16, 42, 34, 911323)),
        ),
        migrations.AlterField(
            model_name='borrowitem',
            name='return_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 23, 16, 42, 34, 911323)),
        ),
    ]
