# Generated by Django 2.1.7 on 2019-03-22 23:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20190323_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='book',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='borrowitem',
            name='borrow_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 23, 0, 27, 43, 180829)),
        ),
        migrations.AlterField(
            model_name='borrowitem',
            name='hand_in_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 23, 0, 27, 43, 180829)),
        ),
        migrations.AlterField(
            model_name='borrowitem',
            name='return_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 23, 0, 27, 43, 180829)),
        ),
        migrations.AlterField(
            model_name='electronic',
            name='broken',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='electronic',
            name='category',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='electronic',
            name='manufacturer',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='electronic',
            name='name',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='electronic',
            name='product_id',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='electronic',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
