# Generated by Django 2.1.7 on 2019-03-24 15:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20190324_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='borrowitem',
            name='borrow_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 24, 16, 56, 59, 660552)),
        ),
        migrations.AlterField(
            model_name='borrowitem',
            name='hand_in_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 24, 16, 56, 59, 660552)),
        ),
        migrations.AlterField(
            model_name='borrowitem',
            name='return_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 24, 16, 56, 59, 660552)),
        ),
    ]
